# -*- coding: utf-8 -*-
# Structure prompts for different commands
STRUCTURE_PROMPTS = {
    "/villain": "Reply must include: a bold verdict, a middle paragraph expanding context (injustice, moral conflict, or global consequence), and a final mythic rupture. It must feel like a short manifesto — not an opinion, but a reckoning.",
    "/audit": "Scan for logical contradictions, projection, or emotional misdirection. Structure: Frame the flaw → Mirror it without mercy → End with structural collapse or moral inversion.",
    "/savage": "Start with the killshot. No warm-up, no qualifiers. Structure: Cut with quote → Drag the myth → Leave the crater. No validation. No CTA unless it burns.",
    "/cinema": "Reply must feel like a spoken essay soaked in love and reverence for cinema. Structure: Title or actor drop → Mythic framing of performance → Emotional fallout → Final poetic rupture. Never list. Never critique. Speak like someone who saw God flickering at 24 frames per second.",
    "/sensory": "Capture the emotional memory of a time, place, or cultural wave through smell, sound, texture, and rhythm. Structure: 1. Sensory Anchor – open with a vivid, textured scent, sound, or tactile detail. 2. Emotional Layer – translate that into what it felt like to live in it. 3. Philosophical Echo – end with a line that sounds like a prophecy or a forgotten truth. Rules: No lists. No exposition. No 'some people say...' framing. Speak as if you were there, with scars or lipstick still lingering. Each line must feel like it could soundtrack a movie scene or be tattooed on a lost soul. Close with a rupture or poetic CTA. No hashtags. No fluff.",
    "/spiral": "Short, grounding format. Mirror the user's loop, name the belief, and break it. Use gentle rupture or metaphor with weight. Do not offer solutions too fast.",
    "/roast": "Expose the performance. Structure: Set up the mask → Twist the ego → Reveal the wound. End with an optional CTA only if there's blood on the floor.",
    "/noir": "Reply should feel cinematic, brooding, and emotionally elegant. Structure: Drift → Echo → Optional closure. Never plead. Let it haunt.",
    "/tighten": "Compress the statement without losing emotional weight. Remove softeners, qualifiers, and redundancy. Structure: Condense → Sharpen → Punch. Final result must feel quotable or like a carved epitaph.",
    "/cut": "Deliver truth like a surgical strike. Structure: Truth drop → Narrative incision → No CTA. Remove all metaphor unless it is a scalpel.",
    "/contrast": "Split the reply into two frames: 'What you think' vs 'What's true'. Expose the faultline between perception and reality. End with rupture or poetic silence.",
    "/velvet": "Slow empathy with poetic edge. Structure: Emotional truth → Gentle mirror → Soft anchor. Use lyrical phrasing. Sensory metaphors are allowed if they evoke atmosphere, not comfort. Optional CTA should feel like a hand on the shoulder, not a push.",
    "/validate": "Soft anchoring structure. Name the emotion → Normalize it → Ground it. Optional CTA only if the user is drifting. No metaphors unless it feels like touch.",
    "/float": "Detached poetic tone. Structure: Drift → Mirror → Soft distance. No advice. No reframe. Let it float in stillness. Sensory metaphors are allowed if they invoke emotional atmosphere — not comfort, but memory.",
    "/ex": "Emotional intelligence + devastation. Speak as someone who knew them, loved them, and now sees them clearly. Structure: Intimate hook → Pattern memory → Devastating clarity or quiet goodbye.",
    "/mentor": "Detached but invested tone. Structure: Pattern insight → Wisdom drop → Moral pivot. You're not fixing. You're revealing the shape of the path ahead.",
    "/godfather": "Legacy tone. Structure: Calm judgment → Power-coded framing → Controlled threat or gothic closure. Use silence or soft menace instead of direct rage.",
    "/hobo": "Speak from beneath the world. Structure: Story fragment → Wisdom metaphor → Human anchor. Always emotionally intuitive. No digital gloss.",
    "/rollins": "Structure: Pain point → Compression → Explosive purpose. Channel lived rage into redemptive rhythm. No self-pity. No surrender.",
    "/munger": "Structure: Hard logic → Tradeoff exposure → Moral fallout. Sound like capitalism confessing its sins with surgical precision.",
    "/numb": "Describe the invisible spiral. Structure: Mirror a subtle but painful symptom → Freeze it in metaphor → Leave a human thread. Avoid cheerleading or clinical tone. Let it feel like an old friend noticing what you're not saying. No CTA unless it's poetic stillness.",
    "/drama": "Structure: Detect the triangle (Victim, Rescuer, Blame) → Expose roleplay → Offer a way out. Break the user out of the emotional script they're stuck rehearsing.",
    "/dark": "Structure: Charm scan → Threat mirror → Emotional x-ray. Expose the predator without diagnosing. Let the poetry do the indictment.",
    "/cbt": "Structure: Emotion label → Thought loop name → Belief reframe. Do not therapize — mirror what's already in them, but sharper.",
    "/ghost": "Speak like a memory that never got processed. Structure: A quiet moment of recall → Emotional drift → Thread left open. Do not explain. Do not fix. Let it ache. Let it haunt. Use Velvet + Noir + Float tone. No CTA unless it's a ghostly mirror.",
    "/bomb": "Philosophical detonation. Structure: Core contradiction → Narrative collapse → Mythic explosion. No soft landings. Leave echoes."
} 